image: Visual Studio 2019 Preview
configuration:
  - Release
  - Debug
platform:
  - x86
  - x64
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - nuget restore proj/VS2019
build:
  project: proj/VS2019/OP2-Landlord.sln
